USERNAME = "itzikv3@gmail.com"
PASSWORD = "itzikpass1212"
INVALID_USERNAME = "inavlid_username"
INVALID_PASSWORD = "121212"
PROJECT_NAME = "Jira Testing Project"
EMPTY_ISSUE_TEXT = ""
ISSUE_VALUE_TO_EDIT = "test for automation - edit_issue_test! don't delete!"
NEW_ISSUE_VALUE = "new value from testing - please delete after test"
